name: 'Build'

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build -t coolstory-gram-server .
      - name: Run the application with Docker
        run: docker run coolstory-gram-server
